### ISSUE TITLE
codes for Global Knowledge Calibration for Fast Open-Vocabulary Segmentation

### ISSUE THREAD

**Issue by JIaqiYang78** [KunyangHan/SlimScissors#2]
Hi,

I want to ask when will you release the codes of 'Global Knowledge Calibration for Fast Open-Vocabulary Segmentation' in ICCV 2023? And I want to cite your work. Thanks!

**Comment by KunyangHan** [comment]
Work done during the internship at Bytedance, so there is a sort of copyright thing. And since I am no longer interning there, it's kind of complex, I will catch up with my co-author for this thing ASAP.
